services:
  database:
    image: postgres:17-alpine3.22
    env_file:
      - ./database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pr-service-network
  backend:
    image: pull_request_service
    build:
      context: ./service
      args:
        - APP_PORT=${APP_PORT:-8080}
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./service/.env
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    networks:
      - pr-service-network

networks:
  pr-service-network:
    driver: bridge